language: php

sudo: false

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "7.1"
    - "nightly"

env:
    matrix:
        - SYMFONY_VERSION=2
        - SYMFONY_VERSION=3
        - SYMFONY_VERSION=4

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

services: postgresql

before_install:
    - psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
    - psql -c 'CREATE TABLE config (name character varying(25) PRIMARY KEY, value character varying(25))' -U postgres -h 127.0.0.1 pomm_test
    - psql -c "INSERT INTO config VALUES ('test', 'value')" -U postgres -h 127.0.0.1 pomm_test
    - psql -c 'CREATE DATABASE pomm_test_2' -U postgres -h 127.0.0.1 postgres
    - psql -c 'CREATE TABLE config (name character varying(25) PRIMARY KEY, value character varying(25))' -U postgres -h 127.0.0.1 pomm_test_2
    - psql -c "INSERT INTO config VALUES ('test', 'value_db2')" -U postgres -h 127.0.0.1 pomm_test_2

    - php -S localhost:8080 -t tests/web &> /dev/null &
    - ln -fs parameters.yml.dist tests/app/config/parameters.yml
    - test "$SYMFONY_VERSION" -eq 2 && composer require --no-update symfony/lts:^2
    - test "$SYMFONY_VERSION" -eq 3 && composer require --no-update symfony/lts:^3
    - cd tests/
    - test "$SYMFONY_VERSION" -eq 2 && composer require --no-update symfony/lts:^2
    - test "$SYMFONY_VERSION" -eq 3 && composer require --no-update symfony/lts:^3
    - cd ..

install:
    - composer update
    - cd tests/
    - composer update
    - rm -rf vendor/pomm-project/pomm-bundle
    - ln -s ../../../ vendor/pomm-project/pomm-bundle

script:
    - ../vendor/bin/phpcs --standard=psr2 --runtime-set ignore_warnings_on_exit true --report=summary ../sources
    - ./bin/behat
    - ./app/console pomm:generate:schema-all default_session_builder
